version: '3'
services:
  server:
    build: ./server
    ports:
      - 3333:3333
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
  client:
    build: ./client
    networks:
      testing_net:
        ipv4_address: 172.28.1.2
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16